# Generated by Django 5.2.17 on 2026-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
